# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: clbernar <clbernar@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/15 18:21:02 by clbernar          #+#    #+#              #
#    Updated: 2023/05/05 13:26:57 by clbernar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CC = cc
FLAGS = -Wall -Werror -Wextra -I.
AR = ar rc
RM = rm -f

HD_DIR = ./Includes
HD = $(HD_DIR)/libft.h $(HD_DIR)/Get_next_line.h $(HD_DIR)/ft_printf.h

GNL_SRCDIR = ./Get_Next_Line
FT_PRINTFDIR = ./Ft_printf

SRCS = ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c ft_isascii.c \
ft_isdigit.c ft_isprint.c ft_itoa.c ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c \
ft_memset.c ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c ft_split.c \
ft_strchr.c ft_strdup.c ft_striteri.c ft_strjoin.c ft_strlcat.c ft_strlcpy.c ft_strlen.c \
ft_strmapi.c ft_strncmp.c ft_strnstr.c ft_strrchr.c ft_strtrim.c ft_substr.c ft_tolower.c \
ft_toupper.c $(GNL_SRCDIR)/get_next_line.c $(GNL_SRCDIR)/get_next_line_utils.c \
$(FT_PRINTFDIR)/ft_format_c.c $(FT_PRINTFDIR)/ft_format_di.c $(FT_PRINTFDIR)/ft_format_p.c \
$(FT_PRINTFDIR)/ft_format_s.c $(FT_PRINTFDIR)/ft_format_u.c $(FT_PRINTFDIR)/ft_format_x.c \
$(FT_PRINTFDIR)/ft_printf_utils.c $(FT_PRINTFDIR)/ft_printf.c $(FT_PRINTFDIR)/ft_stock_arg.c

B_SRCS = ft_lstnew_bonus.c ft_lstadd_front_bonus.c ft_lstsize_bonus.c ft_lstlast_bonus.c \
ft_lstadd_back_bonus.c ft_lstdelone_bonus.c ft_lstclear_bonus.c ft_lstiter_bonus.c \
ft_lstmap_bonus.c

OBJS = $(SRCS:.c=.o)

B_OBJS = $(B_SRCS:.c=.o)

all : $(NAME)

$(NAME) : $(OBJS)
	$(AR) $(NAME) $(OBJS)
	ranlib $(NAME)

bonus : $(B_OBJS)
	$(AR) $(NAME) $(B_OBJS)
	ranlib $(NAME)

cc :
	$(CC) $(FLAGS) main.c -L. -lft

%.o : %.c $(HD)
	$(CC) $(FLAGS) -I $(HD_DIR) -c $< -o $@

clean:
	$(RM) $(OBJS) $(B_OBJS)

fclean: clean
	 $(RM) $(NAME)

re: fclean all

.PHONY : re all fclean bonus clean
